### ISSUE TITLE
Could you release a new version to resolve faraday gem conflict?

### ISSUE THREAD

**Issue by sekiyama58** [rikas/slack-poster#13]
Since currently released v2.2.1 is dependent to `faraday (~> 0.9)`, it conflicts with other gems and very old slack-poster (v2.1.0, using http-party instead of faraday) is selected by bundle, which doesn't work due to 'invalid_payload' error now.

GitHub master, specifiyng `faraday (>= 1.0.0)`, works without conflict.
Could you release this as a new version of the slack-poster gem?

(So far, I am using github master in my Gemfile.)

**Comment by rikas** [comment]
@sekiyama58 just released the updated version (2.2.2). Thanks!
