### ISSUE TITLE
Arguments in readme incorrect

### ISSUE THREAD

**Issue by farski** [rikas/slack-poster#4]
The readme still says `Slack::Poster.new` takes a team, token, and options.

**Comment by rikas** [comment]
Hey @farski

Yes, I did a big revision on the project. Will have to update the README. I'll do it this weekend and I'll let you know when it's ready.

Thanks

**Comment by rikas** [comment]
@farski I've updated the README.md

It's still missing the message attachments part, that I'll add during the weekend :)

Cheers

**Comment by Yue-Li** [comment]
Please update on how to add attachements.

**Comment by rikas** [comment]
@Yue-Li will do, sorry, I didn't have the time I was expecting. Soon...
