### ISSUE TITLE
NameError: uninitialized constant Slack

### ISSUE THREAD

**Issue by luizkowalski** [rikas/slack-poster#8]
Since I updated to 2, I'm seeing this message 

```
irb(main):003:0> Slack::Poster
NameError: uninitialized constant Slack
```

**Comment by Mulkave** [comment]
faced the same issue, probably should be mentioned in the README?

**Comment by kapowaz** [comment]
Had this problem here myself too — should this not be automatically imported into the project’s namespace when you `Bundler.require` ?

**Comment by rikas** [comment]
@kapowaz it should. Which version are you using? As I mentioned before I naively changed to "slack_poster" when releasing the last major version (2.0.0).

Let me know if you still have problems when using the latest version.

**Comment by rikas** [comment]
Ok I think I got it.

It will be solved on the next version (2.1.0) that I'm planing on releasing later today.

Thanks.

**Comment by rikas** [comment]
Ok guys, update to 2.1.0 and let me know if it's working.

**Comment by kapowaz** [comment]
@rikas thanks, that looks like it fixes it!

**Comment by rikas** [comment]
Ok, so I'll consider this solved. Thanks for your feedback.

**Comment by monfresh** [comment]
For anyone else running into this, the proper require statement for version 2.2.0 is as follows:
```ruby
require 'slack/poster'
```
You might not necessarily want to use `Bundler.require`, and if you only want to require the gem where it is needed, the above require statement is the correct one.
