### ISSUE TITLE
How can I mention a user?

### ISSUE THREAD

**Issue by h-teske** [rikas/slack-poster#9]
See https://api.slack.com/docs/formatting

Trying "Hey <@U024BE7LH|bob>, did you see my file?" won't convert the userstring to a proper mention.

**Comment by rikas** [comment]
Hi @h-teske,

I've just tested this out and it worked correctly.

`poster.send_message("<@U04UQC3NF|Daniel> is a nice guy")` converted the message with the right mention to the user on my team.

How are you sending the message? Could you share some code?
